### PR TITLE
Create ban api method

### PR DESCRIPTION
**Pull request by ATXLtheAxolotl**
I'll be adding a kick method also in a few, after that I'll fix `PluginManager.ts`

### CODE REVIEW

**Comment by PMK744** [comment]
Make sure you change the API interface path back to the current.

**Comment by ATXLtheAxolotl** [comment]
Yeah I'll do it, I'm just trying to add a fix method right now

**Comment by ATXLtheAxolotl** [comment]
It'd be very useful if there was a way to use the local pluginAPI instead of the github's pluginAPI

**Comment by PMK744** [comment]
Yea, the reason was that BeWss was compiled to an exe, and there was no way access to the interface that way, and BeRP may eventually make it to an exe. That is why.

**Comment by ATXLtheAxolotl** [comment]
Ah makes sense

**Comment by ATXLtheAxolotl** [comment]
K changed it back to Nobuwu's repository

**Pull request merged**
